version: 2.1

orbs:
  codacy: codacy/base@2.0.1

jobs:
  build_package:
    docker:
      - image: circleci/node:erbium
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Install Autorest dependencies
          command: sudo apt-get install libunwind8
      - run:
          name: Check current version of node and npm
          command: |
            node -v
            npm -v
      - run:
          name: Install dependencies and generate
          command: npm ci
      - run:
          name: Typecheck
          command: |
            npm run check-types
      - run:
          name: Build packages
          command: npm run build
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - lib/
            - node_modules/  

workflows:
  compile:
    jobs:
      - codacy/checkout_and_version
      - build_package:
          requires:
            - codacy/checkout_and_version

