/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const accountId: msRest.OperationParameter = {
  parameterPath: "accountId",
  mapper: {
    required: true,
    serializedName: "accountId",
    type: {
      name: "Number"
    }
  }
};
export const cursor: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "cursor"
  ],
  mapper: {
    serializedName: "cursor",
    type: {
      name: "String"
    }
  }
};
export const limit: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "limit"
  ],
  mapper: {
    serializedName: "limit",
    defaultValue: 20,
    constraints: {
      InclusiveMaximum: 100,
      InclusiveMinimum: 1
    },
    type: {
      name: "Number"
    }
  }
};
export const provider: msRest.OperationURLParameter = {
  parameterPath: "provider",
  mapper: {
    required: true,
    serializedName: "provider",
    type: {
      name: "String"
    }
  }
};
export const search: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "search"
  ],
  mapper: {
    serializedName: "search",
    type: {
      name: "String"
    }
  }
};
export const sort: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sort"
  ],
  mapper: {
    serializedName: "sort",
    type: {
      name: "String"
    }
  }
};
