/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";

const packageName = "";
const packageVersion = "1.0.0";

export class WebsiteAPIContext extends msRest.ServiceClient {
  cursor?: string;
  limit?: number;
  sort?: string;
  search?: string;

  /**
   * Initializes a new instance of the WebsiteAPIContext class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.WebsiteAPIOptions) {
    if (!options) {
      options = {};
    }

    if (!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(undefined, options);

    this.limit = 20;
    this.baseUri = options.baseUri || this.baseUri || "http://localhost";
    this.requestContentType = "application/json; charset=utf-8";
    if (options.cursor !== null && options.cursor !== undefined) {
      this.cursor = options.cursor;
    }
    if (options.limit !== null && options.limit !== undefined) {
      this.limit = options.limit;
    }
    if (options.sort !== null && options.sort !== undefined) {
      this.sort = options.sort;
    }
    if (options.search !== null && options.search !== undefined) {
      this.search = options.search;
    }
  }
}
